### ISSUE TITLE
Feature request - Devices locator without GPS

### ISSUE THREAD

**Issue by happytm** [sh123/esp32_loradv#1]
Thank you for your great project.

It will be nice addition to project to include devices locator with three or more devices at an edge of geographical area of interest. This will eliminate use of GPS  for all devices. Example project is at link below:

https://github.com/sam-hud/radio-locator

Thanks.

**Comment by sh123** [comment]
I don't know, maybe it is just easier to install GPS module :) it will be more precise

**Comment by happytm** [comment]
OK. Thanks.
