### ISSUE TITLE
Is it possible to add Opus for better quality audio?

### ISSUE THREAD

**Issue by happytm** [sh123/esp32_loradv#11]
I know it will reduce range with higher data rate  Opus require but audio quality would be improved. 

I am asking as you implemented Opus codec in your android app version. Can it be done for standalone implementation?

Thanks.

**Comment by sh123** [comment]
That's good idea, I've published OPUS codec as Arduino library https://github.com/sh123/esp32_opus_arduino (also added Arduino libraries registry), loopback i2s example works OK for the first glance, will try to add it to this project.

**Comment by happytm** [comment]
Thank you very much.

**Comment by sh123** [comment]
Added OPUS, could be selected between Codec2/OPUS from settings, seems to work between two transceivers, but did not test very extensively.
