### ISSUE TITLE
Connection diagram

### ISSUE THREAD

**Issue by uw5elk** [sh123/esp32_loradv#13]
Hello.  Is there a diagram for connecting all the modules to the main board?

**Comment by uw5elk** [comment]
In particular, to which pins to connect the display?

**Comment by sh123** [comment]
@uw5elk, ssd1306 display library is using Wire module, which uses esp32 SCL (GPIO22) and SDA (GPIO21) pinouts.

![image](https://github.com/user-attachments/assets/6831df9e-9795-4076-b90c-5d908db22a3d)

**Comment by uw5elk** [comment]
Дякую
