### ISSUE TITLE
ESP32 module 30 pin - which one to use?

### ISSUE THREAD

**Issue by Radiomix2000** [sh123/esp32_loradv#16]
The new PCB layout has halls to ESP32 module with 30 pins. Which one exactly should be used with the latest PCB version?

**Comment by sh123** [comment]
I was using similar to this one, 30 pins, 25mm between left and right pinouts.

![image](https://github.com/user-attachments/assets/4e86b99e-860a-4404-a2e1-6dad7545fb1e)
