### ISSUE TITLE
question about specific use case - one way mic/audio transmission

### ISSUE THREAD

**Issue by B-nutze-RR** [sh123/esp32_loradv#6]
HI, i played around with the lora/codec2 projects and really enjoy to learn from it ! I ask myself it's possible to use 868/915 Mhz lora like the sx1276 and ESP32 to realize a one way audio transmission . I look for a way to transmit on board audio from FPV drones that use a digital video transmission at 5.8Ghz and a 868 lora based control link - I don't look for perfect representation of the onboard audio situation but for a "low latency" representation of the prop noise - rpm and the pitch level of the noise onboard would already be helpful.
In general I want to use one firmware for the sending hardware and one for the receiving side - like ESP-c3 + I2c mic on one side and one with a headphone amp on the other side. 

Would codec2 and 868 Mhz "one-way lora" be able to transmit the noise from a drone or is this type of sound chaos not working for that codec ?

Any idea how latency will behave with decreasing "link quality" in a constant one-way setup ?

THX !!

**Comment by sh123** [comment]
@B-nutze-RR , I do not have any experience with drones, cannot help much, but sending noise over Codec2 does not make much sense, because it is adopted for speech, in other words, it "cuts" non-speech from the spectrum, which might be needed for your purposes.

**Comment by B-nutze-RR** [comment]
@sh123 thanks for clarifying that - looks like missed that part on codec2. 

It might have to work with telemetry data from the flight controller to emulate the "noise" i want. Things like motor RPM and certain PID values can work as audio indicator ( helpful for me personally).
