### ISSUE TITLE
models of ESP32 development boards compatible with the project

### ISSUE THREAD

**Issue by Sergey19880206** [sh123/esp32_loradv#8]
What esp32 board models were successfully used in the project? what boards are not recommended for use in the project?

**Comment by R2AirVlad** [comment]
For using with included PCB version you need a "narrow" ESP32 wroom board like NodeMCU-32S 38P.

**Comment by sh123** [comment]
From software point of view It could be any ESP32 esp32dev (per `platformio.ini`) board. I was using `ESP32 WROOM-32` and board mentioned in previous comment.
